[package]
name = "bloom_filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "*"

[[bin]]
name = "main-2"
path = "src/bin/main-2.rs"
test = true
